### PR TITLE
Add WQHD 1440p presets

### PR DESCRIPTION
**Pull request by prokoudine**
This patch adds WQHD 1440p (2560×1440) frame presets.

### CODE REVIEW

**Comment by jliljebl** [comment]
Thank you, seems to be useful, will merge. 

We can have a lot of these as we have the mechanics for user to hide profiles user is not interested in, but i might consider later making selecting Profiles a two tier process with most common displayed by default and less common shown on user request.

I'll test these on January after Christmas break.

**Comment by prokoudine** [comment]
Or maybe use profiles just for the frame size and put the frame rate into a combo box?

**Comment by jliljebl** [comment]
There are options but from MLT point of view Profiles are atomic so doing frame rate + combo box would require another layer of indirection and hand mapping of some algorithm to auto map, seems more work and potentially a more fragile solution.

**Comment by jliljebl** [comment]
I was thinking a combo box with options "Show common Profiles", "Show all Profiles" that's maybe 30 lines of code and 1 data file.

**Comment by prokoudine** [comment]
> I was thinking a combo box with options "Show common Profiles", "Show all Profiles" that's maybe 30 lines of code and 1 data file.
Makes sense!

**Pull request merged**
