### PR TITLE
Make keyboard shortcuts user configurable #364

### PR DESCRIPTION
**Pull request by dvdlvr**
Shortcuts added as per doc.
This is v0.1 - it adds the custom shortcut functionality, but does not yet do translations of the strings that have hardcoded shortcuts in them. (Like tooltips that say 'Cut - x' instead of 'Cut - [whatever the user selects]' - or the Keyboard shortcuts Help item). That is more involved, but is being worked on.

If you prefer to have a single pull request for all changes together, you can just reject this one.

### CODE REVIEW

**Comment by jliljebl** [comment]
Ok, thank you, this quite a big one. I'll get it read on weekend/early next week and the merge if everything is good.

**Comment by jliljebl** [comment]
Alright, great, seems about as a simple and clean a way to do this as possible. Key names from Gdk function and modifiers state encoded to strings with some if-thens. 

I'll merge and test. We will need add to this later like you said, tool tips are currently hand coded, and long term a GUI component for setting individual key actions would be good but this is perfectly mergeable as.is. Thank you.

This is big enough to possibly introduce a few bugs, but we have a lot of time until next release to hit those in test edits, so I'm not worried at all for the minor destabilizing effect this may have, and i didn't see any bugs while reading the code.

**Comment by jliljebl** [comment]
You should change line 3 the copyright notice in file shortcuts.py to have your name in it and change the year to 2017. I've been lazy on updating the years on another files, but this should clearly be stated to have been created in 2017.

**Comment by jliljebl** [comment]
Did some testing and it works. If we get some problems those can be fixed later, so we can keep this.

**Comment by dvdlvr** [comment]
Alright. Will do.


Sent from Samsung tablet

-------- Original message --------

**Pull request merged**
