### PR TITLE
various filter changes

### PR DESCRIPTION
**Pull request by pmjdebruijn**

### CODE REVIEW

**Comment by pmjdebruijn** [comment]
I've always been trying to get vidstab to work (at least the transform part of it), but it's not quite right yet:
`
    <filter id="vidstab">
        <name>Stabilize</name>
        <group>Fix</group>
        <property name="results" args="editor=file_select exptype=file_resource displayname=Select!file">""</property>
        <property name="smoothing" args="range_in=0,100 displayname=Smoothing">15</property>
        <property name="maxshift" args="range_in=-1,1000 displayname=Max!Shift">-1</property>
        <property name="maxangle" args="range_in=0,180 range_out=0,3.142 displayname=Max!Angle">0.786</property>
        <property name="zoom" args="range_in=-500,500 displayname=Zoom">0</property>
        <property name="optzoom" args="editor=no_editor">1</property>
        <property name="crop" args="editor=no_editor">0</property>
        <property name="relative" args="editor=no_editor">1</property>
        <property name="tripod" args="editor=no_editor">0</property>
        <property name="invert" args="editor=no_editor">0</property>
        <property name="reload" args="editor=no_editor">1</property>
    </filter>
`

**Comment by jliljebl** [comment]
Ok, merging. "Dust" and "Lines" as separate filters do make some sense as "Oldfilm" is quite complex and having these can improve  feature discoverability.

"Grain" can go in "Artistic". The right categorization for this filter isn't super clear to me, but if you believe "Artistic" is more appropriate moving it is fine by me.

I tried vid.stab sometime with no success. There seems to one more filter you could maybe try to see if you get it working, here: https://www.mltframework.org/plugins/FilterAvfilter-deshake/

**Comment by pmjdebruijn** [comment]
Just as a note: Oldfilm, Dust, Lines and Grain are likely to be used together, so having them in the same category seems like a good thing to me.

**Comment by jliljebl** [comment]
Yes, Oldfilm, Dust, Lines and Grain do seem to go together so this new categorization can be more logical to more people then the previous one.

**Pull request merged**
