### PR TITLE
New undo-redo icons

### PR DESCRIPTION
**Pull request by bergamote**
I only realized yesterday that those buttons were undo and redo (always assumed they were related to moving on the timeline), so I did some new icons. Also fixed the tool-tip.

### CODE REVIEW

**Comment by jliljebl** [comment]
Thanks, I'll look at these sometime next week when I do next sessions.

**Comment by jliljebl** [comment]
I merged as these communicate better the function of the buttons, but visually some more work needs to be done at some point. 

These look nice when viewed magnified, but at 100% on screen they seem badly done circles that need some anti-aliasing applied. There are obviously many ways to move forward from here, and I'll be accepting pull requests or trying something myself before the next release.

**Comment by bergamote** [comment]
Thanks for the merge, and I agree it should look smoother. I was trying to match the other icons which are all pixel-sharp, it was a headache to do a curve (so I didn't). But if you're cool with anti-aliased icons, it should be fairly simple. I'll give it a go later today.

**Comment by jliljebl** [comment]
Anti-aliased icons are OK, I have avoided them because many times they were quite difficult for me to get right.

**Comment by bergamote** [comment]
Well, just like you said, at first I couldn't get it to look good. After reading a bit about the pixel grid, I managed to get something, so for future reference here it is:
Re-designed the icons 3 times bigger, tripling the thickness of the lines (3px for 1px, 6px for 2px...). Also made sure the line's distance from the image's top and left edges was multiples of 3px. Shrinking that back down to a third of its size gives a nice anti-aliasing.

**Pull request merged**
