### PR TITLE
Blank clips are now also handled when splitting a sequence into two s…

### PR DESCRIPTION
**Pull request by Bene81**
…equences.

The provided code takes blank clips into consideration when splitting a sequence in two sequences at current play head position.

### CODE REVIEW

**Comment by jliljebl** [comment]
Hi, I didn't click some f''''''g Privacy Notification from Google and didn't get any FLOSS related mail for a few weeks. I just thought it was a bit slow...

I'll look at these in next few days, sorry for the delay.

**Comment by Bene81** [comment]
No worries.

**Comment by jliljebl** [comment]
Ok, everything seems reasonable, I'll  merge and test.

**Comment by Bene81** [comment]
Good. Still need to work on the compositor issue, though. Also I found out that in my environment for some reasons clips in Audio & Video track  > 1 do not get cut.
So I will still have to figure out what is going on there.

**Comment by jliljebl** [comment]
Ok, thanks, on the first quick test the last set of patches seemed to work so we're getting there.

**Pull request merged**
