### PR TITLE
Middle bar with order and show/hide groups of icons

### PR DESCRIPTION
**Pull request by jep-fa**
Middle bar : show and hide groups of icons and order them

In the View menu / Middle bar layout, a new radiobutton is created : Free Toolbar. If you check it, you can choice the visible groups of buttons in the middle bar and move them up or down (left to right in the middle bar). 

Do  Edit menu / Preferences/ Tab Toolbar. Check to make visible or not the buttons on the left. Click on the name of the group : it is selected. Click on the button Up or Down to change the order. Click OK to validate the choices. See immediately the result with View menu / Middle bar layout / Free Toolbar

I wanted to use drag and drop with the Gtk.Listbox but I did'nt find how to do. If somebody knows, I'm interested.

### CODE REVIEW

**Comment by jliljebl** [comment]
I'll create a branch for 6.2.1 release so I can test pull this in master next week.

With this one the question is if I like the GUI approach and that is difficult say from code.

Anyway, I can take action on this before 6.2.1 I'll just do that release on branch and pull into master stuff that will eventually go in 2.8.

**Comment by jep-fa** [comment]
What is 6.2.1 release ?

**Comment by jliljebl** [comment]
It's 2.6.1 obviously, a point release after 2.6. Its a few bug fixes and and I will also try improve on Flatpak which lacks some features currently.

Having done the 6.2.1 typo once I then apparently repeated it, but its now corrected.

**Comment by jliljebl** [comment]
Ok, I merged it.

I mostly like the code, it is something I can easily read and work with but this needs more work on the GUI front. I'll think this over before I comment on changes i think that are needed, then I'll post here or maybe do some patches my self.

Thanks, now that we have this in I can accept new buttons in middlebar as we don't have to make sure that they fit on all screens.

**Comment by jliljebl** [comment]
The one thing I changed was to move middl bar configuration from *Edit->Preferences* dialog to own dialog accessed from *View->Middlebar Layout->Configure Freebar*, and the related code to *middlebar.py*.

The reasoning was that I think that middlebar button configuration GUI is not at application main level that is configured using *Preferences* dialog, it is more naturally presented as part of the subset of features accessed via *View* menu.

I'll post on other needed fixes later

We will need to add code in *middlebar.py* if/when we add new button groups to deal with the fact that prefs data assumes fewer button groups but that should be easy test and append operation.

**Comment by jep-fa** [comment]
Indeed, there were two solutions: either put everything that concerned the middlebar in the preferences or rather do what you achieved by grouping what concerned the middlebar in the View menu
I’m glad the code is easy to understand.

**Comment by jliljebl** [comment]
Did a few more things to integrate the code better:
* added constant values in *appconsts.py*  and used those in both *middlebar.py* and *editorpersistance.py* to identify middlebar gui objects
* added name strings for middlebar gui objects 

Before release we still need:
* fix on the GUI glitch that shows darker colored area under checkbox
* keep moved row selected after using *Up/Down* buttons so that user does not need to re-select item to move it again.

**Comment by jliljebl** [comment]
I did the last two things, this is now good for release.

**Pull request merged**
