### PR TITLE
Sequence Split feature

### PR DESCRIPTION
**Pull request by Bene81**
So finally I found some time to implement the sequence split feature I was suggesting in https://github.com/jliljebl/flowblade/issues/427.

This is my pull request regarding this feature.
As I am still missing the bigger picture about the software architecture I am open for suggestions if you would like to have it structured diffrently.

Also, my fork contains a bug fix for a problem with the TC display edit field. You worked on a bug fix yourself before I had a chance to provide mine. Therefore we came to diffrent solutions. So be careful when merging (although my fork is on your current state.)

### CODE REVIEW

**Comment by jliljebl** [comment]
The code seems to be doing the right kind of things to do the described edit. The structure is the correct one, from menu action to a function in tlineaction.py which uses edit.py EditActions to change the sequnce.

I'll merge now and do more testing tomorrow (maybe Wndesday too)  and report results here.

**Comment by jliljebl** [comment]
There was one bug, when I used the feature in a sequence with 5 videos tracks and 4 audio tracks the created sequence had 4 videos tracks and 5 audio tracks, and moved the clips in track V1 to track A1.

I'll leave the patch merged, because that was fixable with one change, see pushed patch.

screenshot from 2018-04-30 23-39-07

I'll test more tomorrow.

**Comment by jliljebl** [comment]
It sort of works but before release we will need some additional development. Below 3 images, first before "Split Sequence", second the original after split and third the created sequence.
screenshot from 2018-05-01 10-46-07
screenshot from 2018-05-01 10-47-45
screenshot from 2018-05-01 10-46-43

The Issues needing work:

1) Original sequence still has compositors after split. These need to be deleted an moved to new sequence. Pointers:
    *Sequence._create_and_plant_clone_compositor_for_sequnce_clone()*  is good for this (*track_delta* is probably just playhead position),  use *edit.delete_compositor_action()* to delete compositor but keep compositors in list for cloning. *Note compositor.clip_in and compositor.clip_out are timeline positions.*

2) The created sequence is missing blanks in start of seuence, you need insert them manually after calculating how long blank is needed, so 1) detect if playhead is on blank in some track 2) compute how long piece of blank is after playhead, 3) insert them on correct track at index 0 after new sequence is created. Using these methods somehow should get the job:

```python
clip_index  = track.get_clip_index_at(int(playheadpos))
clip = track.clips[clip_index]
clip.is_blanck_clip == True # yes, wrong spelling
clip.length = clip.clip_oiut - clip.clip_in + 1 # out is inclusive
Sequence.create_and_insert_blank(self, track, index, length)
```

3) Change is jarring after sequence creation, call at least *updater.zoom_project_length()* and maybe even *dialogutils.info_message(primary_txt, secondary_txt, parent_window)* to give confirmation on new sequence creation.

4) Move menu item to *Project* menu because thats where other sequence level edit is and change name maybe to *Split to New Sequence at Playhead* to give more info to user.

If you could do these as separate pull requests that would be great. I'm keeping this merged as it can be easily made to work before release sometime maybe September.

**Comment by Bene81** [comment]
Alright. Thanks for the feedback. I will try to make it work according to your description above and will create a new pull request for each fix of the mentioned issues.

**Comment by jliljebl** [comment]
Great. For 2) you will probably also need:

```python
# Get frame of clip.clip_in on timeline.
clip_start_in_tline = track.clip_start(clip_index) 
```

**Pull request merged**
