### PR TITLE
Relinker : replacing destroyed files

### PR DESCRIPTION
**Pull request by jep-fa**
Adds the ability to create missing files even if they do not exist 

I tried to answer to  #958 issue,
For now, only images, audio and video files are concerned.

In the relinker
First check the "Default file for missing files to relink" new button
File by file select a missing file (This is only done for a few files)
then click on the "Set File Relink Path" button 
Save the relinked project.

I'm not sure it's the best way but can you give me your point of view ?
I don't understand why the name of the replaced file stands the name of the origin file. Anyway, it doesn’t matter.
I have to recreate the icons, quit Flowblade and restart it to have the good icons in the media panel and in the timeline.
The folder for the new files is /tmp as indicated in module line 67.

### CODE REVIEW

**Comment by jliljebl** [comment]
Ok, thanks. I have pushed some translations update, but I will be mostly offline regards the project until late this month. Not currently possible to fully test and evaluate this level of complexity change. I will start with testing this when activity resumes. Hopefully once corona passes I will able to keep stuff going without having to take occasional breaks during cycles, but for now these can unfortunately happen sometimes.

**Comment by smolnp** [comment]
@jliljebl, it’s a pity that you didn’t have time to get vaccinated. Get well soon, I hope you will not have any complications. Goodness and health to you.

**Comment by jep-fa** [comment]
I hope you will recover quickly without serious consequences.

**Comment by jliljebl** [comment]
Hi, @jep-fa, @smolnp, there may have been a bit of a miscommunication. 

When I said "Hopefully once corona passes" I wasn't talking about myself getting it, instead I was talking about the effects of the continuing situation on my mental state and ability to effectively maintain responsive communications. This pandemic really rubs me the wrong way, I continually quite pissed off and frustrated and therefore decided to take take a break from active online communications.

Unfortunately the fucking vaccination program is moving so slowly in Finland that it will probably be June before I get vaccinated, so there is still time to actually get it.

I have done some patches and will next fully focus on video/SDL2 sítuation. I will reactivate and start commenting on Issues etc on the 29th, next Monday. Thanks for your concern, really.

**Comment by jliljebl** [comment]
Alright, I'm starting to tackle stuff again. This week I'm spending on building dev environment for MLt and maybe getting first code in and answering stuff here and in forum.

I'll give this session next week and comment more after that.

**Comment by jliljebl** [comment]
@jep-fa Ok, I tested this, here are some points on how we need to develop this:
  * The action of creating a new file to replace a missing one is really an *action*. We do not want to present it as state which changes the functionality of other actions. The solution:
      * crop the checkbox *Default file for missing files to relink*
      * Add a button with text *Create Placeholder File* between the *Set..* and *Delete..* buttons, pressing this creates the file and sets it as the relinked file
  * We can't have project depend on files in */tmp* so we need to to prompt user to select some folder to save the created files into after user presses *Create Placeholder File* button.
  * I have no idea why text 'Coucou' is displayed, so let's just remove that. 
  * The info texts displayed with code like *.msg_label.set_text("Creating Image...")* will not be displayed unless we exit the GTK callback function and launch a new thread to carry out rest of the work. In that thread we need to use *Gdk.threads_enter() Gdk.threads_leave()* pairs around GUI code to not crash. *(In the new thread we are no longer in a GTK callback function and do not have the posession of the global GDK lock and need to acquire it.)*
  * We can't add 'ffmpeg' as dependency just for this feature. We have MLT to create video clips with, so we must use that. If all other points get fixed I can merge this and make video rendering use MLT myself as that is quite easy to do if one has worked with MLT before.

Overall this can be made to work, but we need some changes to get to release quality. I have the branch and if I don't get any updates I'll probably eventually do the fixes myself, but it would be great if you could develop this further towards a released feature.

**Comment by jliljebl** [comment]
@jep-fa For example code in *projectaction.UpdateMediaLengthsThread* shows how we need to work with threads to display updates with processes that take a longer time.

**Comment by jep-fa** [comment]
Thanks for these explanations.

> The action of creating a new file to replace a missing one is really an action. We do not want to present it as state which changes the functionality of other actions. The solution:
>     crop the checkbox Default file for missing files to relink
>     Add a button with text Create Placeholder File between the Set.. and Delete.. buttons, pressing this creates the file and sets it as the relinked file

OK, I'll change this

> We can't have project depend on files in /tmp so we need to to prompt user to select some folder to save the created files into after user presses Create Placeholder File button.

In my mind, this operation is unusual. These files are temporarily created to open a project with a few missing files and quickly replaced by usable clips. Why constrain the user with a complicated operation and not automate the file location ? Can I save them in a folder of another media of the project ?

> I have no idea why text 'Coucou' is displayed, so let's just remove that.

It is a message zone and Coucou can be translated by Hello in French. I'll remove it. I wanted to show the program flow to the user.

> The info texts displayed with code like .msg_label.set_text("Creating Image...") will not be displayed unless we exit the GTK callback function and launch a new thread to carry out rest of the work. In that thread we need to use Gdk.threads_enter() Gdk.threads_leave() pairs around GUI code to not crash. (In the new thread we are no longer in a GTK callback function and do not have the possession of the global GDK lock and need to acquire it.)

I have read that Gdk.threads_enter() and Gdk.threads_leave() were deprecated for new code. I nevertheless tried them but I couldn't use them.
I'll try again.

>   We can't add 'ffmpeg' as dependency just for this feature. We have MLT to create video clips with, so we must use that. If all other points get fixed I can merge this and make video rendering use MLT myself as that is quite easy to do if one has worked with MLT before.

Unfortunatly, I don't know MLT. I'll try to create a colour clip without sound with  patternproducer.create_color_clip(). 
There will remain the sound clips.

**Comment by jliljebl** [comment]
> I have read that Gdk.threads_enter() and Gdk.threads_leave() were deprecated for new code. I nevertheless tried them but I couldn't use them.
I'll try again.

We can try the new method, which i think is:

    while Gdk.events_pending():
        Gtk.main_iteration()

This forces a GUI update without leaving the main tread, no thread needed, this is the new approach I think. The old thing will keep working on GTK 3, when we ever port to GTK 4 we need to stop using it.

>In my mind, this operation is unusual. These files are temporarily created to open a project with a few missing files and quickly replaced by usable clips. Why constrain the user with a complicated operation and not automate the file location ? Can I save them in a folder of another media of the project ?

Ok, let's drop the dialog thing, instead I propose:
  * use *userfolders.get_render_dir()* to get directory to save the files in.
  * create hashed stringname for new clips by using what you have for name now + maybe time of day or some randomness.
  * save file in *userfolders.get_render_dir()*
 
E.g. something like this:

    rand_id_str = str(os.urandom(16))
    clip_id_str = hashlib.md5(rand_id_str.encode('utf-8')).hexdigest() 
    rendered_clip_path = userfolders.get_render_dir() + "/"+ clip_id_str + ".mp4" # or what extension you need

> Unfortunatly, I don't know MLT. I'll try to create a colour clip without sound with patternproducer.create_color_clip().

Leave the ffmpeg usage as is for now, I'll consider adding it as dependency, there could be other uses for it too.

**Comment by jliljebl** [comment]
Ok, I was looking at GPU rendering and seems that the preferred way to test if it is available is to use *ffmpeg*, so we are now going to make *ffmpeg* a dependency because we have two uses for it. Leave *ffmpeg* usage as if you get around to improving this.

**Comment by jep-fa** [comment]
OK, thanks.
I'll create a random name although I would have preferred to keep a reference to the original name. In the .local/share/flowblade/render_clips, it will be easier to remove it than  73ce777e0762a611d454ae7a68febd9f.mp4

I did'nt get to show the flow with  Gdk.threads_enter() and Gdk.threads_leave()  or while Gdk.events_pending(): ... so the user don't know immediatly if pressing the button is effective. For now, l leave it like this.

**Comment by jliljebl** [comment]
Ok,thank you very much for the heavy lifting on this. I fixed the GUI updates and added the button. There could some small issues but it is mostly there.

I added comments that explain how I did this, maybe the GDK/GTK updates model gets explained a bit  better.

**Comment by jep-fa** [comment]
Thank you very much. I will look at this as soon as possible.

**Pull request closed without merging**
