### PR TITLE
Updated Hungarian translations and .pot

### PR DESCRIPTION
**Pull request by ptrg**

### CODE REVIEW

**Comment by jliljebl** [comment]
Hello Peter,

I decided to make the new "Box" and "Ripple" modes for "Overwrite" and
"Trim" tools more user visible by adding strings "Overwrite / Box", "Trim /
Ripple" to tool selector and keyboard shortcuts info. "Box" comes from that
tool being able to do box selections and move clips from multiple tracks,
and "Ripple" comes from that that tool ripples length change on all tracks,
not just the track being trimmed.

This is the last strings fix for 1.12 release now. You may want to add
these changes to your translation, as they are quite prominently visible to
users.


Regards,

Janne

**Comment by ptrg** [comment]
Done... :)

**Comment by jliljebl** [comment]
There are still some kinks to be ironed out in the new modes, but please comment here or mail me on the exact problems you are having as there can alawys be some things I have missed.

**Comment by jliljebl** [comment]
Hi Peter,

I just today after some consideration decided that I still need to asses
some issues on presenting the new tools for users. It may be that I do not
present them in the tool selecting menu, but only make them available via
keyboard shortcuts.

i will make final decision as soon as possible and after i have i push the
_real_ last text changes. This should not take more then a week, I'll send
a mail as soon as I'm done.


Regards,

Janne

**Comment by oluja1973** [comment]
Im not Peter. ;-)
 

Gesendet: Freitag, 03. März 2017 um 15:03 Uhr
Von: jliljebl <notifications@github.com>
An: jliljebl/flowblade <flowblade@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [jliljebl/flowblade] Updated Hungarian translations and .pot (#351)

Hi Peter,

I just today after some consideration decided that I still need to asses
some issues on presenting the new tools for users. It may be that I do not
present them in the tool selecting menu, but only make them available via
keyboard shortcuts.

i will make final decision as soon as possible and after i have i push the
_real_ last text changes. This should not take more then a week, I'll send
a mail as soon as I'm done.


Regards,

Janne

**Comment by jliljebl** [comment]
I tried to get this info to Mario and Peter but I may not have reached
Peter yet.

**Comment by ptrg** [comment]
Hi Janne!

My problems are:

- I can't manage Box mode (of Overwrite tool) to work, it does nothing here but draws a rectangle (which remains on the screen if I press 2 again while drawing it)
- Ripple mode is not clear for me: how it selects positions on other tracks (to drag)

p.s.: I use my name in Hungarian name order, so Péter is my Family name :)

**Comment by jliljebl** [comment]
Hi Gabor,

I'll do a small re-design and post a link here to a tutorial video that explains the tool (or maybe 2 videos, we'll see) and you can then comment if you get it. This will take a few days.

Didn't know about Hungarian name order, so its good that you pointed it out, one does quite naturally assume Peter for first name.

**Comment by jliljebl** [comment]
@ptrg The release for 1.14 is coming and I now have now freezed all the strings for the release.

I committed to that there will be 3 weeks to do the translation before the release after the strings freeze. If you can send the new translation to me by 20th of September 2017 (3 weeks from now) I can guarantee that it will be included in the next release. 

If you can't do the translations right now, feel free to contribute translations later when/if possible for you to do so. 

This is very likely going to be the largest batch of new translations for a single release in the forseeable future. Ever larger amount of future development will happen under the hood and not produce new strings that much.

Maybe the most important new concept in the release is the concept of "Compound Clips" - "Compound" in the sense of "composed of or resulting from union of separate elements" (Merriam-Webster). So these are clips made from 2 or more other clips and/or compositors. Final Cut X has very similar functionality, so if they have a word for this concept in yout language, the same word can probably be used for Flowblade.

Thank you for helping with the project so far.

**Comment by ptrg** [comment]
I'm on it, but there are some issues.

Please check your language updating script, because in its current state a lot of resource strings are removed from my translation files (I did not check others), so they are displayed in English on the GUI. They all seems to be "shortcuts" related...

Also there is a serious bug in preferenceswindow.py that leads to generating invalid po msgid string, see: https://github.com/jliljebl/flowblade/issues/160#issuecomment-297734779

**Comment by jliljebl** [comment]
Hi,


Yes, goddamn it,  I did move shortcut related strings to module
"shortcuts.py" but forgot to add it to create_pot file. This is fixed and
pushed now, thanks for pointing this out.

I will look at the preferences window thing sometime before Monday and mail
you on action taken.


Janne

**Comment by jliljebl** [comment]
Hi,

I can't do any changes for 1.14 anymore. I will do fixes in this area for
1.16, but for now I will not make any changes, I'm just looking for to
getting release out and moving forward.

**Pull request merged**
