### PR TITLE
Color icons for the  middlebar

### PR DESCRIPTION
**Pull request by jep-fa**
This request adds color icons in the middle bar to visualize better the groups of icons. You can choice or not this feature in the Edition menu / Preferences / Wiew

### CODE REVIEW

**Comment by jliljebl** [comment]
Thanks, looks like a nice straight forward way to do this functionality.

I'll pull this immediately after bug fix release 6.2.1 which will not have new strings, so that we don't need translation updates. this does have one and is a new feature so this goes best in for 2.8.

I think 6.2.1 comes on week starting 17th August maybe earlier, hopefully not later, will pull this once that is out.

**Comment by jliljebl** [comment]
Ok, thanks. I can keep this, but we need a few more updates before release:

* there are some visual glitches pointed out below

color_buttons_glitch

* to maintain consistent look we should do the redo and zoom buttons too now, I think

**Comment by jliljebl** [comment]
There was a layout bug in your code, i fixed it with d61a4c46c3ecda169af01675eb0f418bfd8ab607

**Comment by smolnp** [comment]
If it suits you (see the picture below) I can help. I would also like to see colored icons for the light theme and standalone instruments (Titler, Audio Mixer ...).
1RM-XZkX9J0

**Comment by jliljebl** [comment]
@smolnp I'll accept a pull request adding the icons, I think the cut tool is at least more clear. If we have some "artistic differences" between different contributors here, we will deal with them round table collaboration if they occur.

**Comment by smolnp** [comment]
I think that the color of a certain action on the icon should be the same, for example:
# f89013 (or any other) - move arrow (align, lift, offset ...)
# 42c551 (or any other) - video track
# e2fd62 (or any other) - audio track
# 5865e5 (or any other) - adding media
# 4dbbcc (or any other) - entry points of exit
# e63928 (or any other) - clip delete color

For me, there is no fundamental difference which color will be applied for which property, but I am sure that this approach is easier for perception.

I will color some more icons and send you a request.

**Comment by jliljebl** [comment]
@smolnp Let's keep all @jep-fa stuff for time being and first do a 100% additive pull request. Its his idea and initial contribution I  believe we should defer to him on design here and work onward keeping his work the starting point.

**Comment by smolnp** [comment]
I completely agree

**Comment by jep-fa** [comment]
Thanks for your comments.
My idea is that the main color of an icon represents that of the group . So the turquoise blue color of the razor button seems inappropriate to me. I tried to follow the sequence of colors of the rainbow.
I didn’t create any new icons not to disturb the usual users. I only colored the black and white icons.

I had two quick perception problems:

- for the play/stop button: this is the only colored button in the player buttons bar because I failed to enlarge it. I confused it with the button next frame.
- for the undo button, often used: now it is colorized but not the redo button, I see it immediately.
I didn’t feel the need to color the buttons that I use less and I didn’t want to color the interface too much :zoom_buttons and tools buttons.
I agree to @smolnp  "I think that the color of a certain action on the icon should be the same" and I will propose new icons.

**Comment by jliljebl** [comment]
So lets do:
* no more player buttons colored so that play/stop button pops out better
* undo and redo buttons can be colored, but need have some color difference to help with the described perception issue
* add to color to zoom and tools buttons 
* make colored buttons available in light theme too

I'll take the pull requests then they come.

**Comment by smolnp** [comment]
@jep-fa while painting the icons, you simply filled in the background, which in turn spilled over into transparent pixels, so, for example, the icon with a razor blade became incomprehensible. I would advise you to use a 1 pixel brush to control the opacity of the transition to avoid spills.

If Flowblade used all icons in SVG instead of PNG, it would be easier to work with them. Also, the transition between the background and the subject would be perfectly smooth (this is clearly visible on the zoom buttons and buttons with a doubled size for large monitors).

**Pull request merged**
