### PR TITLE
Code changes for User Selectable single Play/Pause button

### PR DESCRIPTION
**Pull request by dvdlvr**
Docs and code changes for user selectable single play/pause button to replace the Play + Stop button.
Selection can be made in preferences window (Editing) or using a command line option (--enable-play-pause / --disable-play-pause).

Comments obviously welcome.

### CODE REVIEW

**Comment by jliljebl** [comment]
Thanks for this. I'm just re-activating on the project after summer break and will look at this next week.

**Comment by dvdlvr** [comment]
My pleasure.

**Comment by jliljebl** [comment]
Ok thanks, everything seems reasonable, so I merged the patch as there have been some other requests for this before so I can assume that there will be a portion of users who find this preferable.

I will do a few changes post merge however:
- I'll remove the command line switch code from app.py, that needs to be kept as simple as possible and command line switch for single pref is nor appropriate
- I'll make the current behavior default, and play/pause optional

**Comment by jliljebl** [comment]
Good job, btw.

**Comment by dvdlvr** [comment]
Thanks :-)

**Comment by dvdlvr** [comment]
Ok, sounds reasonable. Thanks.

**Pull request merged**
