### PR TITLE
Dark theme calm blue

### PR DESCRIPTION
**Pull request by pmjdebruijn**
This fixes a bug, where a background-image set in the system theme will always override the background-color in the flowblade theme.

Also, it changes the fairly saturated/bright blue, to something that fits better with the other colors in the flowblade theme, another blue of the same hue, but less bright and saturated.

It also adds the svg source for all the assets, so they can be easily changed in the future.

### CODE REVIEW

**Comment by pmjdebruijn** [comment]
I just noticed there is still a subtle border issue in the menus, which I can take a look at tomorrow (hopefully).

I'd still appreciate some feedback in the meantime, particularly on whether you agree with the general direction I'm taking this.

**Comment by jliljebl** [comment]
Ok I'll do a quick pull test to see that this is functional.

**Comment by jliljebl** [comment]
No, unfortunately I don't agree with the toning down. For my eye the brighter blue is needed to break the monotony and give rhythm for the GUI.

**Comment by pmjdebruijn** [comment]
Bummer... I didn't quite see that coming...

However, there is a fairly large area between what it is now and to what I changed it to be. Would you consider a half-way version? 

If so I'll update this PR tomorrow. If not then I'll file a new PR with just the CSS fix.

**Comment by jliljebl** [comment]
So here is how I think this should go.

First, let's leave current *../res/css* as is, this the Flowblade Theme.

Create new folder *../res/css_calm* and put your theme CSS and assets folder there.

Change line 262 in *gui.py* to load your stuff from folder *../res/css_calm*.

Once you are satisfied with your theme make a pull request, I'll pull the  *../res/css_calm* folder and add the mechanics that make it possible for user to select this theme, now we have 4 theme selections instead of 3.

Make the theme fully to satisfy *your* sensibility, no half-way anything, the whole point of the exercise is to allow users with different visual presidencies to get what they want.

If you know how, you can add new constant FLOWBLADE_THEME_CALM = 3 into *appconsts.py* and use that to affect colors as you wish.

**Comment by dvdlvr** [comment]
On top of that, why don't we also add a 'custom' folder and write a paper on how to create your own theme - then anyone can put their own creations in the 'custom' folder. Sent from my Huawei tablet-------- Original Message --------Subject: Re: [jliljebl/flowblade] Dark theme calm blue (#709)From: jliljebl To: jliljebl/flowblade CC: Subscribed So here is how I think this should go.
First, let's leave current ../res/css as is, this the Flowblade Theme.
Create new folder ../res/css_calm and put your theme CSS and assets folder there.
Change line 262 in gui.py to load your stuff from folder ../res/css_calm.
Once you are satisfied with your theme make a pull request, I'll pull the  ../res/css_calm folder and add the mechanics that make it possible for user to select this theme, now we have 4 theme selections instead of 3.
Make the theme fully to satisfy your sensibility, no half-way anything, the whole point of the exercise is to allow users with different visual presidencies to get what they want.
If you know how, you can add new constant FLOWBLADE_THEME_CALM = 3 into appconsts.py and use that to affect colors as you wish.

**Comment by pmjdebruijn** [comment]
@jliljebl I'll look into that over the next few days. In the meanwhile I've filed #711 as a bugfix only pull request.

**Pull request merged**
