### PR TITLE
Seq split compositor

### PR DESCRIPTION
**Pull request by Bene81**
Implemented handling of compositors as roughly suggested in https://github.com/jliljebl/flowblade/pull/494
Accidently mixed in a fix for blanks (was branching from the wrong branch).

### CODE REVIEW

**Comment by jliljebl** [comment]
Hi, this is in conflict with master now, could you take look at why that is and fix somehow.

**Comment by Bene81** [comment]
Hi, the problem is, that I have not yet updated my fork with master and I have introduced a method call in the same line where a method call to updater.zoom_project_length() was introduced by one of my previous pull requests.
So, what I could do is, update to master, resolve the conflict and create a new(?) or updated pull request.

**Comment by Bene81** [comment]
Okay, I used the tools from github... did not know this was possible. Would have done this earlier then.
Conflict is resolved.

**Comment by jliljebl** [comment]
Great, I'll pull and test. I'll get back latest tomorrow.

**Comment by jliljebl** [comment]
Ok, I did 5 tests with sequences with compositors and clips on many tracks.

The first test had a problem, but I wasn't able to reproduce it in the next four.

The problem with the first one was not with the created new sequence, problem was in the source sequence. What happened was that in the source sequence a clip went over the length of the sequence so that I couldn't even track playhead to end of displayed sequence. This can happen in Flowblade sometimes when something goes wrong.

Unfortunately I didn't take screenshot on the first attempt so that I don't have clear idea on the arrangement of clips and compositors that made it happen.

Well, this is almost there, next we need to to do some 20 attempts to reproduce this with taking screenshots before doing the split action and playhead being on position.

If we can't reproduce this after trying hard, then we can go ahead with this as is, because rare unreproducable bugs are generally not enough to stop presenting users with useful features.

It can take a few weeks before I have done my tests, you should also try to see if you can get this reproduced.

**Comment by Bene81** [comment]
Hm, sounds familiar. I think I probably can reproduce this.
I would guess now, that it has something to do with a track being marked inactive. I figured out so far that a track not being marked active does not get cut. This makes sense because I am simply calling the tlineaction.cut_pressed() method and this method of course does not cut inactive clips.

These clips not being cut do not get removed because their start lies before playhead position. For some reason flowblade thinks that the end is at playhead position.

This was something I mentioned on a previous pull request somewhere without really understanding the cause back then.
So I will probably refactor cut_pressed a little so it calls a parametrized method which let's us override the analysis of clip.active flag.

Also I found a problem with indices. Somewhere I am generating an off by one. Still need to fix that as well.

Unfortunately I will not be able to work on this before next WE.

**Comment by jliljebl** [comment]
Ok, sounds like this is it now that you mention it. There is no hurry on this at all, next release is earliest September.

**Comment by jliljebl** [comment]
I added a cut tool and now there is "cutmode.cut_all_tracks(frame)" method available which can be good here.

**Comment by Bene81** [comment]
This sounds like it would then be just a single line replacement. I will try it this evening.

**Pull request merged**
