### PR TITLE
Fix for #184 + Hungarian translation

### PR DESCRIPTION
**Pull request by ptrg**
Updated translations (caused by the fix for #184 "DEL key issue" in jliljebl's flowblade)
Hungarian translation added (depending on the fix for #184)

### CODE REVIEW

**Comment by jliljebl** [comment]
Thanks for this. I'm just re-activating on the project after summer break and will look at this next week.

**Comment by jliljebl** [comment]
Thanks for the Hungarian translation, and some other fixes that we're done. These require quite a lot of work at this point as there is surprisingly lot of text to translate, so quite a lot of work was needed to get this done.

I hope Flowblade finds many Hungarian users who can benefit from your work.

In the future you should turn off the automatic whitespace cleaner you probably have on your editor as it makes finding the actual code changes much more difficult. If this was just a code patch I would have required a resubmit without the whitespace fixes, but for this particular case of a new language translation contribution I was willing to spend the time to find the changes.

**Comment by ptrg** [comment]
The changes I made in some .py files are enclosing #184 related string literals in _(....)
The structure (indentation) of the source code did not change , however the extra spaces (at the end of lines) were automatically removed by my editor (as you said). These spaces (at eol) are not required by python to parse the code correctly, they only increase the size of the source code. So (unfortunately in this case) I did not care about them too much, because I always remove extra spaces in all of my source codes written in any languages. Sorry, if I made extra work for you.
Thank you very much for merging my work into your great software!

**Comment by jliljebl** [comment]
No problem with the spaces, Geany just seems to add 4 spaces on new lines, so my work flow in its current way produces a bit of unnecessary white spaces and removing them in the same patch as doing code changes makes it a bit more difficult to asses code changes. Thanks for your contribution.

**Pull request merged**
