### PR TITLE
Keyframededitor: match Flowblade theme colors

### PR DESCRIPTION
**Pull request by pmjdebruijn**
As I mentioned I think the keyframeeditor also sticks out a bit, here a single change to make it fit better into the theme.

It would be even better if these colors would be abstracted away into the CSS though.

### CODE REVIEW

**Comment by jliljebl** [comment]
Let's see how this works out.

**Comment by jliljebl** [comment]
Well, this does have better contrast for keyframes, I'll keep it.

**Comment by jliljebl** [comment]
Yeah, this an improvement.

**Comment by jliljebl** [comment]
Thanks, I have done some versions on this before and it didn't occur to me to use the blue in the center line.

Colors are indeed all over the place and should refactored into single module that all widgets would query for colors.

**Comment by pmjdebruijn** [comment]
At least this provides a short-term stop-gap until that becomes reality.

**Pull request merged**
