### PR TITLE
Add Lossless FFv1 profile

### PR DESCRIPTION
**Pull request by lsde**
Encoding parameters taken from https://amiaopensource.github.io/ffmprovisr/#create_FFV1_mkv

### CODE REVIEW

**Comment by jliljebl** [comment]
Seems that this can be found useful by some users and patch looks good, merged.

**Comment by jliljebl** [comment]
However, this will not be immediately available to users on all systems, my Ubuntu seems to be missing the .mkv container for example.

**Comment by jliljebl** [comment]
Is the name of the container format matroska but file ending mkv? I'll test if my code needs special case for this.

**Comment by lsde** [comment]
Exactly, matroska container format name in lavf is different than the file extension.

**Comment by jliljebl** [comment]
Yeah, i needed to special case it in code to make it available, so it will not appear as available unless the version >= with the patch I just pushed is used. This will all be working for 1.14, I did a test render and it worked just fine with your new encoding. Thanks for adding this.

**Pull request merged**
