### PR TITLE
Add USB jog/shuttle support to Flowblade

### PR DESCRIPTION
**Pull request by ratherlargerobot**
Initially, the Contour Design family of jog/shuttle devices is supported.
This includes the ShuttlePRO v2, and the ShuttleXpress. There are also
quite a few rebranded devices that are basically the ShuttleXpress under
another name. Those devices are likely to work as well. I have attempted
to make the USB and driver code extensible, to make it easier to add
additional devices in the future.

The USB implementation is handled by PyUSB, which in turn depends on
libusb version 1. Flowblade connects directly to the configured USB device
and uses its own userspace drivers to connect/disconnect, and handle input
events.

All USB features are off by default. To turn them on, a user has to go to
Edit -> Preferences -> Jog/Shuttle, and then enable it. On that window, a
driver must also be selected.

The core drivers themselves are in the usbhiddrivers module. However, a
res/usbhid/ file contains XML files that specify which lower-level driver
to use within Flowblade, some USB connection settings, and also map keys
on the device to events.

Flowblade already has great support for user-mappable keys from the keyboard.
However, in order to allow a USB device to trigger specific actions when its
keys are pressed, a new targetactions module was created. The USB HID driver
config XML files use the same "code" action names that the existing keyboard
shortcuts feature uses. Hopefully we can unify these systems more over time.

Users can also configure their own custom key mapping by copying and editing
a USB HID driver config file in their own local user folder. For example,
the flowblade-trunk/Flowblade/res/usbhid/foo.xml file could be copied into
~/.local/share/flowblade/user_usbhid/foo.xml, and edited to taste.

### CODE REVIEW

**Comment by dvdlvr** [comment]
Good luck 😊And thanks for your effort on this. I'll be sure to check it out. RegardsStevenSent from my Huawei tablet-------- Original message --------From: Nathan Rosenquist ***@***.***>Date: Sun, 20 Feb 2022, 22:55To: jliljebl/flowblade ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [jliljebl/flowblade] Add USB jog/shuttle support to Flowblade (PR #1052)
By the way, I bought a Blackmagic Davinci Resolve Speed Editor USB control device, with the hopes of figuring out how to integrate it into Flowblade. That one looks like more of a challenge than the Contour Design ShuttleXpress, since it requires both USB input and output, and some sort of handshake to get the device to send input at all. Wish me luck!

**Comment by Disaster2life** [comment]
Not much to comment on due to my lack of experience with actual code, but maybe it would be worth mentioning in the main document, probably under interacting with the timeline section something along the lines of "Using Shuttle" or just "using external devices to edit" to allow for room for expansion, also probably could condense this better information wise 

```
in both forward and reverse, and navigating frame by frame are right at your fingertips.

Turning the jog wheel to the right and left moves the playback location forward and backward, one frame at a time, respectively.

Turning the shuttle ring to the right starts out with playback in the forward direction, with increasingly faster speeds the farther you turn the shuttle.

Turning the shuttle ring to the left starts out with playback in the reverse direction, with increasingly faster speeds the farther you turn the shuttle.
```
Maybe this?

```
In both forwards and reverse, navigating frame by frame, right at your fingertips.

Turning the jog wheel to the right and left moves the playback forward and backward, one frame at a time respectively,

Turning the shuttle ring leftwards or rightwards starts playback in reverse or forward, and for faster or slower playback, turn the ring more in that direction.
```

Also I had a question for this function, so this would basically serve as a gradient on the speed of the playback, or will it basically be a remapped J, K, and L key function?

~~could have put all this in a pull request but I'm afk and GitHub on mobile is kinda annoying~~

**Comment by Disaster2life** [comment]
@ratherlargerobot ah thanks, also you might have accidentally removed a bit of the line since `one frame a time.` doesn't make sense, just a heads-up, 

And the jog wheel seems like a super useful, think that's actually more than flowblade itself allows you to speed up/ go in reverse of I remember correctly, I was thinking of just getting a secondary keyboard and programming that to perform functions directly (read the idea I raised a while back to allow keyboards to do that) but yeah getting a compatible product might actually be way more useful

**Comment by dvdlvr** [comment]
Just a reminder that the arrow keys have modifiers attached to them to increase speed with a factor which you can set yourself in preferences. Eg Shift right could go at 2x speed and Ctrl right at 3x speed, which means ShiftCtril right would go at 2*3= 6x speed. If I remember right this doesn't affect the jkl keys, but not entirely sure. I always use the arrow keys. Sent from my Huawei tablet-------- Original message --------From: Nathan Rosenquist ***@***.***>Date: Sat, 26 Feb 2022, 21:28To: jliljebl/flowblade ***@***.***>Cc: dvdlvr ***@***.***>, Mention ***@***.***>Subject: Re: [jliljebl/flowblade] Add USB jog/shuttle support to Flowblade (PR #1052)
@Disaster2life good catch! I gave the document one more round of proofreading.
And yes, you are correct, the shuttle implementation here does allow for more levels of speed in both directions than the J/K/L keys. I think the J/K/L keys are great the way they are. It's a balance between getting different speeds, and not pressing the keys too many times. It would be annoying to press the J or L key 7 times just to get it to go at its top speed. But with the shuttle, you just turn the ring about 60 degrees and you've gone through all 7 speeds on your way up to the fastest one.
I spent a fair amount of time during development just playing around with the jog/shuttle on a timeline, to make sure that the feel is just right.

**Comment by Disaster2life** [comment]
The Doc seems good now, nothing else I can catch, and yeah to me at least, the J,K, L keys are just rough movement tools on the timeline, having to press them several times before it actually allows you to, _use them that way would defeat their purpose_, but the shuttle definitely mixes the function of them and the arrow keys with the amount of control, and the curve you later mentioned is pretty good, personally don't see the function of a x32 factor, since at that point it might be better to just use the mouse and go back to whatever section, but that also involves moving your hand off of the shuttle so maybe? 

An interesting idea for the shuttle could be allowing a modifier key + the wheel to have some actions? That could allow for some cool possibilities like skipping around the timeline on the basis of markers if that's useful? 

Also totally didn't know about the modifiers to the arrow keys, thanks for informing me about that, probably would be useful in my usage

**Comment by jliljebl** [comment]
I'll look at this after 2.10.

**Comment by luzpaz** [comment]
Can this be reviewed or at least rebased for testing purposes?

**Comment by jliljebl** [comment]
Ok, I'll do it merge on test branch first thing after 2.12. This has been unfortuinately left behind a bit I'll get to it soon.

**Comment by jliljebl** [comment]
Ok, I pulled the PR as local branch *usb-jog-feature* and did the following:
  * merged with master
  * fixed the conflicts
  * fixed a circular imports problem, some added new imports in master obviously  didn't work with import the structure of the pull request
  * pushed the feature branch back to origin here

@ratherlargerobot can you test that the feature branch *usb-jog-feature* still works as intended?

**Comment by jliljebl** [comment]
@ratherlargerobot I added the JOG_SHUTTLE.md file contents as section *Jog / Shuttle Support* in help docs chapter *Advanced Editing Features*. Thanks for providing the text, this will make using the feature and adding new devices much easier to users.

**Comment by jliljebl** [comment]
The release and Flatpak is out now. @ratherlargerobot, if you could test the Flatpak sometime so we could get a confirmation that this works with the Flatpak.

**Comment by jliljebl** [comment]
> If I had to guess, maybe Flatpak has to find libusb within a Flatpak library, and not from the main OS, where libusb is already installed?

Yeah, obviously. Somehow I thought this was part of the platform (the lib, not the bindings) and because it didn't crash on startup I thought that to be proven. Not true.

I added the needed line:

```
  - shared-modules/libusb/libusb.json
```

and pushed an update. Updates usually take about 6 hours to go live, I'll post here once libusb update seems to be available. 

Then you can simply do: 

```
flatpak update
```

and try again.

**Comment by jliljebl** [comment]
Oh I forgot, you can pull the test version once the build completes, I'll post link to that here in about half an hour.

**Comment by jliljebl** [comment]
Test build is ready. You can install it with:

```
flatpak install --user https://dl.flathub.org/build-repo/93677/io.github.jliljebl.Flowblade.flatpakref
```

This is now a "user" install, so need to run it with a flag:

```
flatpak run -u io.github.jliljebl.Flowblade
```

**Comment by jliljebl** [comment]
I'll go merge the patch that might drop the test build. I'll comment once the new build is up.

**Comment by jliljebl** [comment]
The build with *libusb* is live now and can be tested with re-install or updating existing install:

```
flatpak update
```

**Comment by jliljebl** [comment]
@ratherlargerobot Hey, one more thing. I hacked in  slowmo playback with timers for JKL searching (at 0.35x speed), and then extended the USB shuttle code to support it too, see the patches below.

JKL patch: https://github.com/jliljebl/flowblade/commit/65078510287d284b5f12cc60dafb5f9e8e8640b3

USB patch: https://github.com/jliljebl/flowblade/commit/0c7d36bff278338daf95c9451fbeb915a138ca84

I'm 90% sure that USB thing works too, but if you could test this one more thing that would be great.

**Comment by jliljebl** [comment]
Ok, removed the 32x speeds for now https://github.com/jliljebl/flowblade/commit/3b5a001feef98cc2d8ae81ddbbc05703e9a5d873

If everything works, you can test and see if you think some other values would be better. I'll take a patch if you have improvements.

**Pull request merged**
