### PR TITLE
Dvdlvr patch 694 big buttons

### PR DESCRIPTION
**Pull request by dvdlvr**
This patch contains the changes to allow bigger buttons when the Double Height is selected for tracks in the Preferences -> View.
A detail of the changes can be found in the patch document in the docs directory.
This will increase the size of all image buttons, but not text buttons, as well as the Big TimeCode display. All light and dark buttons are twice the width+height but for the 2 stock images on the Render tab (File open and Save As) I selected slightly bigger stock images.

### CODE REVIEW

**Comment by jliljebl** [comment]
Hi, I'll be doing next session on Tuesday or Wednesday. I'll read this and give give feedback then

**Comment by jliljebl** [comment]
II'm merging. The approach looked to be nice and correct: new icons + layer of indirection with method for getting correct size icon, .

I had done a lot of Python 3 conversion work on a brach but we luckily only had one conflict. Your patch may have something that wont work on Python 3 but I changed master to Python 3 and merged your stuff anyway. 

Now that master is Python 3 you need MLT bindings post this commit: 
https://github.com/mltframework/mlt/commit/f702ed6d881eb9462dd33a510b07698bc4ee8440 to run it.

I'll add some info on creating bindings for Python 3 on weekend but I'm having a flu here and will only do this merge today.

**Comment by jliljebl** [comment]
We can't change anything on editorpersistance.EditorPreferences, your change *double_track_hights ->  double_track_height* crashes here and on every other system with:

Traceback (most recent call last):
  File "/home/janne/codes/flowblade/flowblade/flowblade-trunk/flowblade", line 91, in <module>
    app.main(modules_path)
  File "/home/janne/codes/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 236, in main
    _set_draw_params()
  File "/home/janne/codes/flowblade/flowblade/flowblade-trunk/Flowblade/app.py", line 859, in _set_draw_params
    if editorpersistance.prefs.double_track_height == True:
AttributeError: 'EditorPreferences' object has no attribute 'double_track_height'

Yes, it is misspelled but stability concerns override these kinds of correctness viewpoints so I'll roll that back.  

I think this happened to to me once or twice, changing code in development updates the prefs fille on disk in such a way that the chance seems to work, but any other system crashes on launch.

**Comment by jliljebl** [comment]
And now everything seems to work excellently, thank you.

I only have 1080px monitors which makes doing these changes here quite difficult, so getting these in the project with contributions is great.

**Comment by dvdlvr** [comment]
Very weird. Obviously I tested that and I ran alternatively a standard 
2.2 and my modified version of 2.2 several times, from 2 local github 
directories and I never saw a crash, but I agree stability is more 
important.
Fixing typos is good for future maintenance, but stability is key.
Thanks for the update.

**Comment by dvdlvr** [comment]
Thanks. It's a pleasure working on this. I use it all the time so it 
benefits me greatly as well :-)

**Comment by jliljebl** [comment]
I created a rough guide to create and run Python 3 bindings, maybe it is useful for you:

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/creating_user_folder_bindings.md

**Pull request merged**
