### PR TITLE
Profilefixups

### PR DESCRIPTION
**Pull request by pmjdebruijn**
Fixes a whole bunch of minor niggles with regard to the renderencodings

### CODE REVIEW

**Comment by jliljebl** [comment]
Merged. I'll do some testing and may have questions later, but changes seem improvements on first read,

**Comment by jliljebl** [comment]
Looks good, merged.

Did you test that we do not lose projects saved with duplicate profiles? if not, that still needs to be tested.

**Comment by pmjdebruijn** [comment]
I wasn't aware that was an issue. Since the duplicate projects and complete duplicates, including the description, they four pairs of bit identical files. 

I assumed saved projects would reference the description string, not the filename?

**Comment by jliljebl** [comment]
We have to test and read code. We do want to get rid of duplicates, so I'm keeping this but needs a bit further work so that we can be sure that we are breaking peoples projects on next release.

**Pull request merged**
