### PR TITLE
Update INSTALLING.md

### PR DESCRIPTION
**Pull request by faridosc**

### CODE REVIEW

**Comment by jliljebl** [comment]
I googled  Yaourt and arclinux wiki said:

Warning: Yaourt is an unofficial, third-party script that is not supported by the Arch Linux developers

So not knowing much about Arch, what's rationale of using Yaourt here instead of Pacman?

**Comment by Miniellipse** [comment]
Yaourt is a script that can be used to install software provided by more sources than pacman. In most cases it is used to install software provided by the AUR-repository. AUR-software in most cases is software provided as sourcecode, providing scripts to make installation possible to users that don't want to dive into arch-linux that deep.
Yaourt can search the AUR and other repositories for software and install it the easy way. Pacman has very limited possibilities for searching, so yaourt can be an alternative, when installing "normal" packages, yaourt does the same as pacman without the need to exacltly know the name of the software cause of the search possibility's.

**Comment by jliljebl** [comment]
Ok, sounds reasonable. I'll merge as-is, but this needs some formatting later to mention repository install commands for other Oses.

**Comment by faridosc** [comment]
i agree that it could get better :)

**Pull request merged**
