### PR TITLE
Fixes for sequence split

### PR DESCRIPTION
**Pull request by Bene81**
- Fixed the remaining artifacts in previous sequence when tracks were inactive. cutmode.cut_all_tracks did the trick
- Fixed the "off by one" when cutting blank clips. Inclusive/Exclusive misinterpretation was the cause.

### CODE REVIEW

**Comment by jliljebl** [comment]
Merged, testing next.

**Comment by jliljebl** [comment]
Ok, passed the activity switch test and this is now ready. I will do a bit more testing still, but unless I find something this is ready for release. Congrats, this is the first contribution manipulating timeline in a major way, might be first doing anything to timeline at all. 

I'll add you to "Developers" list, do you want "Bene81" or your real name? Your name wasn't on git log, so I don't have it. Post here what you wish.

If you find time and inclination to do further contributions, open an issue if its a big thing or post comment on "in feature queue" Issues if you find some of those interesting to make sure I'm not just then working on those. I really need to add a short text on contributing code, will come in a few weeks.

Thank you for work on Flowblade and Linux video editing, these are improving, but never as fast as everyone would wish.

**Comment by Bene81** [comment]
Hey, thanks.
I think I am just fine with a reference to Bene81 on github.

I surely will keep using flowblade and therefore if I come across a feature I would like or I miss I will probably take the means to get it into flowblade. And thanks for pointing to the "in feature queue" issues. I might take a look, if I find something in there that I would like to do.

Thanks also for supporting me to get my ideas and workflow integrated into flowblade.

**Comment by jliljebl** [comment]
Added you as Bene81 into "Developers".

This cycle has been a lot about supporting workflows different from my own, and this approach will continue from now on.  If stuff comes with reasonable code (like yours) I'll put it in if I understand the use case and can somehow fit in with existing design.

**Pull request merged**
